# build.ps1 - Bundle all JS modules into a single file
#
# Usage: .\build.ps1
#
# This script concatenates all module files in dependency order
# to create a single bundle file for production deployment.
# This reduces HTTP requests to 1, improving load time.

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$outputFile = Join-Path $scriptDir "eventAnnotationsPlot.bundle.js"

# Module order (dependency order — config before state, axon before evals, App.js last)
$modules = @(
    "constants/config.js",
    "constants/state.js",
    "utils/chartLoader.js",
    "utils/axon.js",
    "utils/transformers.js",
    "utils/interactions.js",
    "utils/skysparkVars.js",
    "evals/loadExecSummary.js",
    "evals/loadTotalEventCost.js",
    "evals/loadUtilityCost.js",
    "evals/loadPowerData.js",
    "evals/loadSiteName.js",
    "evals/loadEventDates.js",
    "utils/rendering/chart.js",
    "utils/rendering/annotations.js",
    "utils/rendering/timeline.js",
    "utils/rendering/labels.js",
    "utils/rendering/tooltips.js",
    "components/Table.js",
    "components/Widgets.js",
    "components/EventDetail.js",
    "components/ExpandView.js",
    "components/EventsDatabase.js",
    "fixtures/generators.js",
    "App.js"
)

# Header comment for the bundle
$header = @"
/**
 * Event Annotations Plot - Bundled
 *
 * This file is auto-generated by build.ps1
 * Do not edit directly - modify the source modules instead.
 *
 * Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
 */

"@

# Clear or create output file
Set-Content -Path $outputFile -Value $header -Encoding UTF8

Write-Host "Building bundle: $outputFile" -ForegroundColor Cyan
Write-Host ""

$totalSize = 0
foreach ($module in $modules) {
    $modulePath = Join-Path $scriptDir $module

    if (Test-Path $modulePath) {
        $content = Get-Content -Path $modulePath -Raw -Encoding UTF8
        $fileSize = (Get-Item $modulePath).Length
        $totalSize += $fileSize

        # Add module separator comment
        $separator = "`n// ═══════════════════════════════════════════════════════════════`n// Module: $module`n// ═══════════════════════════════════════════════════════════════`n"

        Add-Content -Path $outputFile -Value $separator -Encoding UTF8
        Add-Content -Path $outputFile -Value $content -Encoding UTF8

        Write-Host "  [OK] $module ($([math]::Round($fileSize / 1024, 1)) KB)" -ForegroundColor Green
    } else {
        Write-Host "  [SKIP] $module (not found)" -ForegroundColor Yellow
    }
}

$bundleSize = (Get-Item $outputFile).Length
Write-Host ""
Write-Host "Bundle created successfully!" -ForegroundColor Green
Write-Host "  Total source: $([math]::Round($totalSize / 1024, 1)) KB"
Write-Host "  Bundle size:  $([math]::Round($bundleSize / 1024, 1)) KB"
