# build.ps1 — Bundle Event Cost V2 into a single JS file
#
# Usage: .\build.ps1
# Concatenates all source modules in dependency order.

$ErrorActionPreference = "Stop"

$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceDir  = Join-Path $scriptDir "eventCostV2"
$outputFile = Join-Path $sourceDir "eventCostV2.bundle.js"

$modules = @(
    "constants/config.js",
    "constants/state.js",
    "utils/chartLoader.js",
    "utils/axon.js",
    "utils/transformers.js",
    "utils/interactions.js",
    "utils/skysparkVars.js",
    "evals/loadEventCostResults.js",
    "evals/loadBookingTable.js",
    "evals/loadPowerData.js",
    "evals/loadSiteName.js",
    "utils/rendering/chart.js",
    "utils/rendering/annotations.js",
    "utils/rendering/timeline.js",
    "utils/rendering/labels.js",
    "utils/rendering/tooltips.js",
    "components/MonthlyOverview.js",
    "components/UtilityReconciliation.js",
    "components/EventDetailV2.js",
    "components/SiteStatus.js",
    "components/ExpandView.js",
    "components/Documentation.js",
    "App.js"
)

$header = @"
/**
 * Event Cost V2 — Bundled
 * Auto-generated by build.ps1. Do not edit directly.
 * Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
 */

"@

Set-Content -Path $outputFile -Value $header -Encoding UTF8
Write-Host "Building bundle: $outputFile" -ForegroundColor Cyan
Write-Host ""

$totalSize = 0
foreach ($module in $modules) {
    $modulePath = Join-Path $sourceDir $module
    if (Test-Path $modulePath) {
        $content  = Get-Content -Path $modulePath -Raw -Encoding UTF8
        $fileSize = (Get-Item $modulePath).Length
        $totalSize += $fileSize

        $separator = "`n// ═══════════════════════════════════════`n// Module: $module`n// ═══════════════════════════════════════`n"
        Add-Content -Path $outputFile -Value $separator -Encoding UTF8
        Add-Content -Path $outputFile -Value $content   -Encoding UTF8

        Write-Host "  [OK] $module ($([math]::Round($fileSize / 1024, 1)) KB)" -ForegroundColor Green
    } else {
        Write-Host "  [SKIP] $module (not found)" -ForegroundColor Yellow
    }
}

$bundleSize = (Get-Item $outputFile).Length
Write-Host ""
Write-Host "Bundle complete!" -ForegroundColor Green
Write-Host "  Source: $([math]::Round($totalSize / 1024, 1)) KB"
Write-Host "  Bundle: $([math]::Round($bundleSize / 1024, 1)) KB"
